import { IDatePickerStrings } from "office-ui-fabric-react";

export const DatePickerStrings: IDatePickerStrings = {
  months: [
    "Enero",
    "Febrero",
    "Marzo",
    "Abril",
    "Mayo",
    "Junio",
    "Julio",
    "Agosto",
    "Septiembre",
    "Octubre",
    "Noviembre",
    "Diciembre",
  ],
  shortMonths: [
    "Ene",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dic",
  ],
  days: [
    "Domingo",
    "Lunes",
    "Martes",
    "Miércoles",
    "Jueves",
    "Viernes",
    "Sábados",
  ],
  shortDays: ["D", "L", "M", "M", "J", "V", "S"],
  goToToday: "Ir a fecha actual",
  prevMonthAriaLabel: "Ir al mes anterior",
  nextMonthAriaLabel: "Ir al próximo mes",
  prevYearAriaLabel: "Ir al año anterior",
  nextYearAriaLabel: "Ir al año próximo",
  closeButtonAriaLabel: "Cerrar",
  isRequiredErrorMessage: "La fecha es requerida.",
  invalidInputErrorMessage: "Formato inválido.",
};
